### ISSUE TITLE
user/password when using single-user-mode

### ISSUE THREAD

**Issue by Hans-Maulwurf** [hugosenari/tt-rss-mobilete#3]
hello,

i don't know if it's an issue or just a mistake by myself. what do i have to enter for user/passwird when i'm using tt-rss in single-user-mode? i already set the password for the user "admin" and tried to login on tt-rss-mobilete with this credentials, but it still says wrong user/password?

**Comment by hugosenari** [comment]
Hi,

Excuse my delay to answer, I'm from Brazil and we are in carnival this week...

You had can try:
- Call this on terminal

```
curl 'http://YOUR_DOMAIN/api/' -X POST -d '{"op":"login","user":"admin","password":"YOUR_PASSWORD_HERE"}'
```

My response:

```
{"seq":0,"status":0,"content":{"session_id":"blablablablabla","api_level":7}}
```
- Disable single-user-mode and test your login/pass

I enabled single-user-mode here and is working to me.

**Comment by hugosenari** [comment]
Closed, this bug seems to be TT-RSS bug not TT-RSS-Mobilete.
